@startuml Rxjs
interface Observer<T> {}


class Observable {
    {static} bindCAllback(func: Fn, selector: Fn, scheduler: Scheduler): Observable
    + subscribe(observerOrNext: Observer|Function, error, complete): ISubscription
}

 Observable <|-- ConnectableObservable
 Observable <|-- GroupedObservable
 Observable <|-- Subject

 class Subscription {}
 note left of Subscription: 表示可以清理的资源，流对象订阅后返回可清理对象

 Subscription <|-- Action
 Subscription <|-- Subscriber

@enduml