@startuml 四大国有保险集团（中国人寿、中国人保、中国太平、中信保）
:保险集团;
fork
    :1949中国人民保险公司;
    :1996中国人寿保险有限公司;
    :1999中国人寿保险公司;
    :2003中国人寿保险（集团）公司（中国人寿601628）;
    fork
        :中国人寿保险股份有限公司（人寿龙头）;
    fork again
        :中国人寿资产管理有限公司（机构投资者，全牌照）;
    fork again
        :中国人寿财产保险股份有限公司;
    fork again
        :中国人寿养老保险股份有限公司;
    fork again
        :中国人寿电子商务有限公司;
    fork again
        :中国人寿保险（海外）股份有限公司;
    fork again
        :国寿投资控股有限公司;
    fork again
        :国寿健康产业投资有限公司;
    fork again
        :广发银行股份有限公司;
    fork again
        :保险职业院校;
    end fork
    :业务范围：寿险、产险、企业和职业年金、银行、基金、资产管理、财富管理;
fork again
    :中国人保PICC;
    :1949中国人民保险公司;
    :1996中国人民保险（集团）公司;
    :1998撤销拆分中国人民保险（集团）公司;
    :1999中国人民保险公司;
    :2018中国人民保险集团股份有限公司（中国人保601319）;
fork again
    :中国太平洋保险（集团）股份有限公司（中国太保601601）;
fork again
    :中国平安保险（集团）股份有限公司（中国平安601318）;
fork again
    :新华人寿保险股份有限公司（新华保险601336）;
fork again
    :内蒙古西水创业股份有限公司（西水股份600291）;
fork again
    :天茂实业集团股份有限公司（天茂集团000627）;
fork again
    :中国太平保险集团有限责任公司（中国太平，港股上市）;
    :控股国华人寿保险股份有限公司;
fork again
    :中信保;
end fork;
@enduml