@startmindmap
* React Events
** Clipboard Events
    *** onCopy
    *** onCut
    *** onPaste
** Composition Events
    *** onCompositionEnd
    *** onCompositionStart
    *** onCompositionUpdate
** Keyboard Events
    *** onKeyDown/keydown
    *** onKeyPress/keypress
    *** onKeyUp/keyup
** Focus Events
    *** onFocus
    *** onBlur
** Form Events
    *** onChange
    *** onInput
    *** onInvalid
    *** onReset
    *** onSubmit
** Generic Events
    *** onError
    *** onLoad
** Mouse Events
    *** onClick
    *** onContextMenu
    *** onDoubbleClick
    *** onDrag/drop
    *** onDragEnd/dragend
    *** onDragEnter/dragenter
    *** onDragExit
    *** onDragLeave/dragleave
    *** onDragOver/dragover
    *** onDragStart/dragstart
    *** onDrop/drop
    *** onMouseEnter
    *** onMouseLeave
    *** onMouseMove
    *** onMouseOut
    *** onMouseOver
    *** onMouseUp
** Pointer Events
    *** onPointerDown/pointerdown
    *** onPointerUp/pointerup
    *** onPointerMove/pointermove
    *** onPointCancel/pointercancel
    *** onGotPointerCapture/gotpointercapture
    *** onLostPointerCapture/lostpointercapture
    *** onPointerEnter/pointerenter
    *** onPointerLeave/pointerleave
    *** onPointerOver/pointerover
    *** onPointerOut/pointerout
** Selection Events
    *** onSelect/select
** Touch Events
    *** onTouchCancel/touchcancel
    *** onTouchEnd/touchend
    *** onTouchMove/touchmove
    *** onTouchStart/touchstart
** UI Events
    *** onScroll/scroll
** Wheel Events
    *** onWheel/wheel
** Media Events
    *** onAbort
    *** onCanPlay
    *** onCanPlayThrough
    *** onDurationChange
    *** onEmptied
    *** onEncrypted
    *** onEnded
    *** onError
    *** onLoadedData
    *** onLoadedMetadata
    *** onLoadStart
    *** onPause
    *** onCanPlay
    *** onPlaying
    *** onProgress
    *** onRateChange
    *** onSeeked
    *** onSeeking
    *** onStalled
    *** onSuspend
    *** onTimeUpdate
    *** onVolumeChange
    *** onWaiting
** Image Events
    *** onLoad
    *** onError
** Animation Events
    *** onAnimationStart
    *** onAnimationEnd
    *** onAnimationIteration
** Transition Events
    *** onTransitionEnd
** Other Events
    *** onToggle
@endmindmap