@startuml select嵌套关系
skinparam class {
    BackgroundColor<<react>> #00a3aa
    ArrowColor<<react>> #00a3aa
    BorderColor<<react>> #00a3aa

    BackgroundColor<<first>> #00a3fe
    ArrowColor<<first>> #00a3fe
    BorderColor<<first>> #00a3fe
}

class React.Component<<react>> {}
class SelectControl<<first>> {}
class Select<<first>> {}
class BaseTransferRenderer<<first>> {}
class Transfer<<first>> {}
class TransferDropDown {}
class SelectControlRenderer {}
note bottom
SelectControlRenderer就是type:select
end note
class MultiSelectControlRenderer {}
note bottom
MultiSelectControlRenderer就是type:multi-select
end note
class TransferDropdownRenderer {}
class PopOverContainer<<first>> {}
class ResultBox<<first>> {}


React.Component <|--> SelectControl
React.Component <|--> Select
React.Component <|--> BaseTransferRenderer
React.Component <|--> Transfer
React.Component <|--> PopOverContainer
React.Component <|--> ResultBox

SelectControl <|--> SelectControlRenderer
SelectControl <|--> MultiSelectControlRenderer
SelectControl *--> TransferDropdownRenderer
SelectControl *--> Select

BaseTransferRenderer <|--> TransferDropdownRenderer
BaseTransferRenderer *--> Transfer
TransferDropdownRenderer *--> TransferDropDown
Transfer <|--> TransferDropDown

TransferDropDown *--> PopOverContainer
TransferDropDown *--> ResultBox

@enduml