@startuml amis store设计

interface IStore {
    + string storeType;
    + string id;
    + string path;
    + string parentId?;
    + any [propName: string];
}

interface index.RendererStore {
    + RendererStore storeType;
    --views--
    + get fetcher()
    + get notify()
    + get isCancel()
    + get __()
    + get stores()
    + any getStoreById(string: id)
    --actions--
    + any addStore(IStore store)
}
note top
    渲染器的store管理器，即props.rootStore
    RendererStoreManager名字更合适
    配合manage.js中的store做store的管理
    rootStore就是store管理器，类型是RendererStore
    区分topStore，根store，类型是RootStore，顶层数据域
end note

interface node.StoreNode {
    + string id
    + string path
    + string storeType
    + boolean disposed
    + string parentId
    + []string childrenIds
    --views--
    
    --actions-- 
}

node.StoreNode <|-- iRenderer.iRendererStore

interface iRenderer.iRendererStore {
    + boolean hasRemoteData
    + Object data
    + number initedAt
    + number updatedAt
    + Object pristine
    + any action
    + boolean dialogOpen
    + any dialogData
    + boolean drawerOpen
    + any drawerData
    --views--
    
    --actions-- 
}

iRenderer.iRendererStore <|-- service.ServiceStore
interface service.ServiceStore {
    + string msg
    + boolean error
    + boolean fetching
    + boolean saving
    + boolean busying
    + boolean checking
    + boolean initializing
    + any schema
    + string schemaKey
    --views--

    --actions-- 
}

service.ServiceStore <|-- form.FormStore
interface form.FormStore {
    + boolean inited
    + boolean submited
    + boolean submiting
    + any savedData
    + boolean canAccessSuperData
    + string|boolean persistData
    + []any allFieldError

    --views--

    --actions-- 
}

node.StoreNode <|-- formItem.FormItemStore
interface formItem.FormItemStore {
    + boolean isFocused
    + string type
    + string label
    + boolean unique
    + boolean loading
    + boolean required
    + boolean isValueSchemaExp
    + any tmpValue
    + any emitedValue
    + object rules
    + object messages
    + []any errorData
    + string name
    + string itemId
    + boolean unsetValueOnInvisible
    + []string itemsRef
    + boolean validated
    + boolean validating
    + boolean multiple
    + string delimiter
    + string valueField
    + string labelField
    + boolean joinValues
    + boolean extractValue
    + []any options
    + boolean expressionsInOptions
    + boolean selectFirst
    + any autoFill
    + boolean clearValueOnHidden
    + any validateApi
    + []any selectedOptions
    + []any filteredOptions
    + any dialogSchema
    + boolean dialogOpen
    + any dialogData
    + any resetValue
    + boolean validateOnChange
    + object inputGroupControl
    --views--
    
    --actions-- 
}

formItem.FormItemStore <--* formItem.ErrorDetail 
interface formItem.ErrorDetail {
    + string msg;
    + string tag;
    + string rule;
}

service.ServiceStore <|-- app.appStore
interface app.appStore {

}

iRenderer.iRendererStore <|-- combo.ComboStore
interface combo.ComboStore {

}

combo.ComboStore <--* combo.UniqueGroup
interface combo.UniqueGroup {

}

service.ServiceStore <|-- crud.CRUDStore
interface crud.CRUDStore {

}

iRenderer.iRendererStore <|-- list.ListStore
interface list.ListStore {

}

list.ListStore <--* list.Item
interface list.Item {

}

service.ServiceStore <|-- modal.ModalStore
interface modal.ModalStore {

}

iRenderer.iRendererStore <|-- pagination.PaginationStore
interface pagination.PaginationStore {

}

service.ServiceStore <|-- root.RootStore
interface root.RootStore {
    + types.frozen() runtimeError
    + types.frozen() runtimeErrorStack
    + types.frozen() query
    ---views---
    + get downStream()
    ---actions---
    + updateContext(context)
    + updateLocation(location, parseFn)

}

interface status.StatusStore {}

iRenderer.iRendererStore <|-- table.TableStore

interface table.TableStore {}

table.TableStore <--* table.Column
interface table.Column {}

table.TableStore <--* table.Row
interface table.Row {}

service.ServiceStore <|-- table2.TableStore2

interface table2.TableStore2 {}

table2.TableStore2 <--* table2.Column
interface table2.Column {}

table2.TableStore <--* table2.Row
interface table2.Row {}



@enduml