@startuml 股权控制图

start
fork
    :天津远璞企业管理咨询有限公司\n\n贾鹏翔(董事长、经理)\n张立胜（董事）\n吕昕（董事）\n厉嘉锋(董事)\n徐恬恬(监事);
    -> 45%;
fork again
    fork
    :车建兴;
    -> 92%;
    fork again
    :车建芳;
    -> 8%;
    end fork
    :红星美凯龙控股集团有限公司\n\n车建兴（董事长）\n车建芳（副董事长）\n潘平（总经理）\n孙宴卿（财务负责人）\n储琴华（监事）;
    -> 28%;
fork again
    :Allied Smart Asia Pacific Limited\n\n 没查出来信息;
    ->100%;
    :天津远鹄企业管理咨询有限公司\n\n王洪辉（董事长）\n吕昕（董事）\n张立胜（董事）\n段莹莹（监事）\n贾鹏翔（经理、董事）;
    ->100%;
    :天津远璞企业管理咨询有限公司\n\n贾鹏翔(董事长、经理)\n张立胜（董事）\n吕昕（董事）\n厉嘉锋(董事)\n徐恬恬(监事);
    ->100%;
    :上海煦程企业管理有限公司\n\n彭凛凛(执行董事)\n徐晔(监事);
    -> 21%;
fork again
    :其他小股东;
end fork
->100%;
:重庆远洋红星企业发展有限公司\n(重庆红星美凯龙企业发展有限公司)\n\n贾鹏翔(董事长)\n徐国峰(副董事长)\n张楠(监事)\n陈淑红(懂事兼经理)\n厉嘉锋（董事）\n姜南(懂事)\n刘敏(监事)\n葛强(董事)\n赵罡(董事);
->100%;
:常州远弘置业有限公司\n\n贾鹏翔(董事长)\n徐国峰(副董事长)\n韩红玲(总经理)\n张楠(监事)\n葛强(董事)\n赵罡(董事);
->100%;
:常州洛星企业管理有限公司\n\n韩维清(董事长兼总经理)\n董博(董事)\n舒维伟(董事)\n徐恬恬(监事);
->100%; 
:上海洛星企业管理有限公司\n\n韩维清(董事长兼总经理)\n董博(董事)\n舒维伟(董事)\n苏锋()\n徐恬恬(监事);
->100%;
:上海洛景企业管理有限公司\n\n金苹（总经理）\n苏锋(财务)\n厉嘉锋（执行董事）\n徐恬恬（监事）;
end
@enduml