name: Webapp autodeploy https://tigerwfh.github.io
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.3.0
        with:
          folder: build
          branch: gh-pages
